language: python
python:

  - "3.6"

script: 

  - python ENV_Create.py
  - python Keyboard_mapping_and_screen_shot.py
  - python main.py
  - python Network_model.py
  - python test.py
  - python train.py

install: pip install --user -r requirements.txt
